--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/MydSkill
build-by-default: true
branches:
- main
projects:
  MydSkill:
    path: ""
    libs:
      - src: Muqsit/InvMenu/Invmenu
        branch: "pm5"
        version: ^4.6.5
      - src: jojoe77777/FormAPI/libFormAPI
        branch: master
        version: ^2.1.1
      - src: cooldogedev/libSQL/libSQL
        branch: "pm5"
        version: ^0.2.6
...
